# WARNING:
# Do not use this file as a template for you repository TravisCI configuration
# Instead use the files under the "/sample_files" directory for that purpose.

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  - VERSION="master" ODOO_REPO="odoo/odoo"
  - VERSION="master" ODOO_REPO="OCA/OCB"
  - VERSION="8.0"
  - VERSION="7.0"
  - VERSION="6.1"
  # - VERSION="6.0"  # Test script not ready for v6.0

install:
  - cp -r ../maintainer-quality-tools/ $HOME
  - mv tests/test_repo/* ./
  - export PATH=$HOME/maintainer-quality-tools/travis:$PATH
  - travis_install_nightly $VERSION

script:
  - travis_run_flake8
  - travis_run_tests ${VERSION}

#after_success:
#  coveralls
